# Generated by Django 3.2.10 on 2022-02-01 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fama',
            fields=[
                ('famahale', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='хна')),
                ('famaname', models.CharField(max_length=255, unique=True, verbose_name='фирма')),
            ],
        ),
        migrations.CreateModel(
            name='Hara',
            fields=[
                ('harahale', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='хна')),
                ('haraname', models.TextField(unique=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Mala',
            fields=[
                ('malahale', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='хна')),
                ('malaname', models.CharField(max_length=255, unique=True, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Tafa',
            fields=[
                ('tafahale', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='хна')),
                ('tafaname', models.CharField(max_length=255, unique=True, verbose_name='телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Pere',
            fields=[
                ('perehale', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='персона')),
                ('famahale', models.ForeignKey(db_column='famahale', on_delete=django.db.models.deletion.CASCADE, to='perso.fama', verbose_name='фирма')),
                ('harahale', models.ForeignKey(db_column='harahale', on_delete=django.db.models.deletion.CASCADE, to='perso.hara', verbose_name='url')),
                ('malahale', models.ForeignKey(db_column='malahale', on_delete=django.db.models.deletion.CASCADE, to='perso.mala', verbose_name='email')),
                ('tafahale', models.ForeignKey(db_column='tafahale', on_delete=django.db.models.deletion.CASCADE, to='perso.tafa', verbose_name='телефон')),
            ],
        ),
    ]
