# Generated by Django 3.2.10 on 2022-02-01 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fara',
            fields=[
                ('farahale', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='хна')),
                ('faraname', models.CharField(max_length=255, unique=True, verbose_name='форма')),
            ],
        ),
        migrations.CreateModel(
            name='Maka',
            fields=[
                ('makahale', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='хна')),
                ('makaname', models.CharField(max_length=255, unique=True, verbose_name='марка')),
            ],
        ),
        migrations.CreateModel(
            name='Mara',
            fields=[
                ('marahale', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='хна')),
                ('maraname', models.CharField(max_length=255, unique=True, verbose_name='мера')),
            ],
        ),
        migrations.CreateModel(
            name='Mata',
            fields=[
                ('matahale', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='хна')),
                ('mataname', models.CharField(max_length=255, unique=True, verbose_name='материал')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('razahale', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='хна')),
                ('razaname', models.CharField(max_length=255, unique=True, verbose_name='размеры')),
            ],
        ),
        migrations.CreateModel(
            name='Sata',
            fields=[
                ('satahale', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='хна')),
                ('sataname', models.CharField(max_length=255, unique=True, verbose_name='стандарт')),
            ],
        ),
        migrations.CreateModel(
            name='Sava',
            fields=[
                ('savahale', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='хна')),
                ('savaname', models.CharField(max_length=255, unique=True, verbose_name='сэвалюта')),
            ],
        ),
        migrations.CreateModel(
            name='Teve',
            fields=[
                ('tevehale', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='тэвалюта')),
                ('farahale', models.ForeignKey(db_column='farahale', on_delete=django.db.models.deletion.CASCADE, to='curcy.fara', verbose_name='форма')),
                ('makahale', models.ForeignKey(db_column='makahale', on_delete=django.db.models.deletion.CASCADE, to='curcy.maka', verbose_name='марка')),
                ('marahale', models.ForeignKey(db_column='marahale', on_delete=django.db.models.deletion.CASCADE, to='curcy.mara', verbose_name='мера')),
                ('matahale', models.ForeignKey(db_column='matahale', on_delete=django.db.models.deletion.CASCADE, to='curcy.mata', verbose_name='материал')),
                ('razahale', models.ForeignKey(db_column='razahale', on_delete=django.db.models.deletion.CASCADE, to='curcy.raza', verbose_name='размеры')),
                ('satahale', models.ForeignKey(db_column='satahale', on_delete=django.db.models.deletion.CASCADE, to='curcy.sata', verbose_name='стандарт')),
            ],
        ),
        migrations.CreateModel(
            name='Solo',
            fields=[
                ('solohale', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='сэляви')),
                ('savahale', models.ForeignKey(db_column='savahale', on_delete=django.db.models.deletion.CASCADE, to='curcy.sava', verbose_name='сэвалюта')),
                ('tevehale', models.ForeignKey(db_column='tevehale', on_delete=django.db.models.deletion.CASCADE, to='curcy.teve', verbose_name='тэвалюта')),
            ],
        ),
    ]
