# Generated by Django 3.2.10 on 2022-02-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hala',
            fields=[
                ('halahale', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='хна')),
            ],
        ),
    ]
