# Generated by Django 3.2.10 on 2022-02-01 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perso', '0001_initial'),
        ('curcy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zovo',
            fields=[
                ('zovohale', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='заявка')),
                ('zovokalebe', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='заколичество')),
                ('zovokalepe', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='отколичество')),
                ('perehale', models.ForeignKey(db_column='perehale', on_delete=django.db.models.deletion.CASCADE, related_name='zeguzoba', to='perso.pere', verbose_name='персона')),
                ('tevehalebe', models.ForeignKey(db_column='tevehalebe', on_delete=django.db.models.deletion.CASCADE, related_name='pezedaya', to='curcy.teve', verbose_name='заберу')),
                ('tevehalepe', models.ForeignKey(db_column='tevehalepe', on_delete=django.db.models.deletion.CASCADE, related_name='pekulene', to='curcy.teve', verbose_name='отдам')),
            ],
        ),
    ]
